site_name: LiteVectors
site_url: https://litevectors.org
site_description: Lightweight binary serialization format
# copyright: LitePipe LLC
# repo_url: https://github.com/LitePipe/litevectors.org
# repo_name: LitePipe/litevectors
markdown_extensions:
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
extra_css: 
  - stylesheets/extra.css
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  custom_dir: docs/override
  features:
    - navigation.instant
    #- navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
  # palette:
  #   # Palette toggle for light mode
  #   - media: "(prefers-color-scheme: light)"
  #     scheme: default
  #     # primary: indigo
  #     # accent: deep orange
  #     toggle: 
  #       icon: material/brightness-7
  #       name: Switch to dark mode
  #   # Palette toggle for dark mode
  #   - media: "(prefers-color-scheme: dark)"
  #     scheme: slate
  #     # primary: indigo
  #     # accent: teal
  #     toggle:
  #       icon: material/brightness-4
  #       name: Switch to light mode